services:
  proxy:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./api-gateway/.env
    networks:
      - app-network
    depends_on:
      - redis
      - user-service
      - product-service
    environment:
      - APP_TOKEN_SECRET=need_to_change
      - APP_PORT=4000
      - USER_SERVICE_URL=http://user-service:4001
      - PRODUCT_SERVICE_URL=http://product-service:4002
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  user-service:
    build:
      dockerfile: Dockerfile
      context: ./user-service
    container_name: user-service
    ports:
      - "4001:4001"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    environment:
      - APP_TOKEN_SECRET=need_to_change
      - PORT=4001
      - MONGO_URI=mongodb://mongodb:27017/user_service
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  product-service:
    build:
      dockerfile: Dockerfile
      context: ./product-service
    container_name: product-service
    ports:
      - "4002:4002"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - PORT=4002
      - MONGO_URI=mongodb://mongodb:27017/product_service

  mongodb:
    image: mongo:6
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
