name: Deploy app to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Build Frontend
        working-directory: ./fe
        run: |
          npm install
          echo "VITE_API_URL=http://${{ secrets.EC2_IP }}:4000/" > .env
          npm run build

      - name: Copy backend and frontend build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: |
            be/
            fe/build/
          target: "/home/${{ secrets.EC2_USER }}/ap_shoppingonline"

      - name: Run docker-compose for backend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/ap_shoppingonline/be
            docker compose down || true
            docker compose pull || true
            docker compose -f docker-compose.production.yml up -d --build

      - name: Build and Run Frontend Container on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/ap_shoppingonline/fe

            docker stop react-fe-container || true
            docker rm react-fe-container || true
            docker build -t react-frontend .
            docker run -d -p 80:80 --name react-fe-container react-frontend
