name: Deploy app to EC2

on:
  push:
    branches: [main]

env:
  APP_DIR: "/home/${{ secrets.EC2_USER }}/ap_shoppingonline"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check secrets
        run: |
          if [ -z "${{ secrets.EC2_IP }}" ] || [ -z "${{ secrets.EC2_USER }}" ] || [ -z "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ]; then
            echo "One or more secrets are not set. Exiting..."
            exit 1
          fi

      - name: Copy backend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: be/*
          target: "${{ env.APP_DIR }}"

      - name: Ensure Docker is installed on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi
            if ! command -v docker-compose >/dev/null 2>&1; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            sudo usermod -aG docker ${{ secrets.EC2_USER }}

      - name: Run docker-compose for backend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.APP_DIR }}/be
            docker compose down || echo "No containers to stop"
            docker compose pull || echo "No images to pull"
            docker compose -f docker-compose.production.yml up -d --build
            docker ps -a
